# Generated by Django 5.1.7 on 2025-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundesland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundesland', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Klassenstufe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klassenstufe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lerninhalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerninhalt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach_titel', models.CharField(max_length=100)),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.bundesland')),
                ('klassenstufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.klassenstufe')),
            ],
        ),
        migrations.CreateModel(
            name='Lernfeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lernfeld', models.CharField(max_length=100)),
                ('unterrichtseinheiten', models.IntegerField()),
                ('fach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.fach')),
            ],
        ),
        migrations.CreateModel(
            name='Lerninhalt_Beschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerninhalt_beschreibung', models.TextField()),
                ('lerninhalt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lerninhalt')),
            ],
        ),
        migrations.CreateModel(
            name='Lernziele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lernziel', models.CharField(max_length=100)),
                ('lernfeld_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lernfeld')),
            ],
        ),
        migrations.CreateModel(
            name='Lernziele_Beschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lernziel_beschreibung', models.TextField()),
                ('lernziel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lernziele')),
            ],
        ),
        migrations.CreateModel(
            name='Teilziele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teilziel', models.CharField(max_length=100)),
                ('lernziele_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lernziele')),
            ],
        ),
        migrations.AddField(
            model_name='lerninhalt',
            name='teilziel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.teilziele'),
        ),
        migrations.CreateModel(
            name='Teilziele_Beschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teilziel_beschreibung', models.TextField()),
                ('teilziel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.teilziele')),
            ],
        ),
    ]
