# Generated by Django 5.1.7 on 2025-04-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehrplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klassenstufe', models.PositiveIntegerField()),
                ('bundesland', models.CharField(max_length=100)),
                ('fach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lerninhalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lernbereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('unterrichtsstunden', models.PositiveIntegerField()),
                ('lehrplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernbereiche', to='curriculum.lehrplan')),
            ],
        ),
        migrations.CreateModel(
            name='LerninhaltBeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lerninhalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beschreibungen', to='curriculum.lerninhalt')),
            ],
        ),
        migrations.CreateModel(
            name='Lernziel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lernbereich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernziele', to='curriculum.lernbereich')),
            ],
        ),
        migrations.CreateModel(
            name='LernzielBeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lernziel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beschreibungen', to='curriculum.lernziel')),
            ],
        ),
        migrations.CreateModel(
            name='Teilziel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lernziel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilziele', to='curriculum.lernziel')),
            ],
        ),
        migrations.AddField(
            model_name='lerninhalt',
            name='teilziel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lerninhalte', to='curriculum.teilziel'),
        ),
        migrations.CreateModel(
            name='TeilzielBeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('teilziel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beschreibungen', to='curriculum.teilziel')),
            ],
        ),
    ]
