# Generated by Django 5.1.7 on 2025-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehrplan',
            name='klassenstufe',
            field=models.CharField(help_text="Mehrere Klassenstufen durch Komma trennen, z.\u202fB. '3, 4, 5a'", max_length=100),
        ),
    ]
