# Generated by Django 5.1.7 on 2025-04-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_lehrplan_klassenstufe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lehrplan',
            old_name='klassenstufe',
            new_name='klassenstufen',
        ),
    ]
