# Generated by Django 5.1.7 on 2025-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_klassenstufe_lehrplan_klassenstufen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lehrplan',
            options={'ordering': ['bundesland', 'fach', 'klassenstufen'], 'verbose_name': 'Lehrplan', 'verbose_name_plural': 'Lehrpläne'},
        ),
        migrations.AlterModelOptions(
            name='lernbereich',
            options={'ordering': ['lehrplan', 'nummer'], 'verbose_name': 'Lernbereich', 'verbose_name_plural': 'Lernbereiche'},
        ),
        migrations.AlterModelOptions(
            name='lerninhalt',
            options={'ordering': ['teilziel', 'id'], 'verbose_name': 'Lerninhalt', 'verbose_name_plural': 'Lerninhalte'},
        ),
        migrations.AlterModelOptions(
            name='lerninhaltbeschreibung',
            options={'verbose_name': 'Lerninhaltbeschreibung', 'verbose_name_plural': 'Lerninhaltbeschreibungen'},
        ),
        migrations.AlterModelOptions(
            name='lernziel',
            options={'ordering': ['lernbereich', 'id'], 'verbose_name': 'Lernziel', 'verbose_name_plural': 'Lernziele'},
        ),
        migrations.AlterModelOptions(
            name='lernzielbeschreibung',
            options={'verbose_name': 'Lernzielbeschreibung', 'verbose_name_plural': 'Lernzielbeschreibungen'},
        ),
        migrations.AlterModelOptions(
            name='teilziel',
            options={'ordering': ['lernziel', 'id'], 'verbose_name': 'Teilziel', 'verbose_name_plural': 'Teilziele'},
        ),
        migrations.AlterModelOptions(
            name='teilzielbeschreibung',
            options={'verbose_name': 'Teilzielbeschreibung', 'verbose_name_plural': 'Teilzielbeschreibungen'},
        ),
        migrations.AlterField(
            model_name='lehrplan',
            name='klassenstufen',
            field=models.CharField(help_text="Mehrere Klassenstufen durch Komma trennen, z. B. '3, 4, 5a'", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='lernbereich',
            unique_together={('lehrplan', 'nummer')},
        ),
    ]
